name: 'Daily Job'

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  run_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Python script
      run: python main.py

    - name: Convert TXT to M3U
      run: |
        for txtfile in $(find . -name 'merged_output.txt'); do
          m3ufile="${txtfile%.txt}.m3u"
          python txt_to_m3u.py "$txtfile" "$m3ufile"
        done
      
    - name: Upload generated files
      uses: actions/upload-artifact@v2
      with:
        name: generated-files
        path: |
          merged_output.txt
          others_output.txt
          
    - name: Commit changes
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add merged_output.txt
          git add merged_output.m3u
          git add others_output.txt
          git commit -m "AutoUpdate generated files"

          current_datetime=$(date +"%Y%m%d_%H%M%S")
          cp merged_output.txt history/"${current_datetime}_merged_output.txt"
          cp others_output.txt history/"${current_datetime}_others_output.txt"
          git add history/"${current_datetime}_merged_output.txt"
          git add history/"${current_datetime}_others_output.txt"
          git commit -m "Archive file with timestamp"
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
        
